@protocol = HTTP/1.1
@host = http://localhost
@port = 4001
@baseUrlByPostId = /posts/{{postId}}/comments
@baseUrl = /posts/comments
@urlByPostId = {{host}}:{{port}}{{baseUrlByPostId}}
@url = {{host}}:{{port}}{{baseUrl}}
@contentTypeJson = application/json
@postId = 43ea959c

### findAll posts
GET {{url}} {{protocol}}
Content-Type: {{contentTypeJson}}

### findAll posts by postId
GET {{urlByPostId}} {{protocol}}
Content-Type: {{contentTypeJson}}

### save
POST {{urlByPostId}} {{protocol}}
Content-Type: {{contentTypeJson}}

{
    "content": "comment3"
}